#!/bin/sh

set -e

# Check if we're running inside a snap (SNAP environment variable exists)
if [ -n "$SNAP" ]; then
    # Snap environment - use absolute paths with $SNAP
    export TERM=xterm-256color
    exec "$SNAP/usr/lib/jvm/java-17-openjdk-amd64/bin/java" \
     -jar "$SNAP/pava.jar" "$@"
else
    # Regular environment - use relative paths
    exec java -jar ./pava.jar "$@"
fi