name: pava
version: '1.0'
summary: Pava Interpreter
description: |
  Pava is a simple Tree-walking interpreter built using Java.
grade: stable
confinement: strict
base: core20

parts:
  # Part for the Java runtime
  openjdk:
    plugin: nil
    stage-packages:
      - openjdk-17-jre-headless  # Bundle the Java runtime

  # Part for your JAR and launcher script
  pava:
    plugin: dump
    source: .
    organize:
      pava: usr/bin/pava  # Move the launcher script to usr/bin/
    stage:
      - pava.jar  # Stage the JAR file
      - usr/bin/pava  # Stage the launcher script

  # Part for the .pava library files
  pava-lib:
    plugin: dump
    source: ./src/main/lib
    organize:
      '*.pava': usr/share/pava/  # Move .pava files to usr/share/pava/

apps:
  pava:
    command: usr/bin/pava  # Points to the launcher script
    plugs: [network]
    environment:
      PAVA_LIB_DIR: $SNAP/usr/share/pava