name: pavalang
version: '1.0'
summary: Pava Interpreter
description: |
  Pava is a simple Tree-walking interpreter built using Java that combines the syntax of Python with the goodness of Java. This snap builds the project using Maven,
  packages the resulting JAR along with a launcher script, and ensures the required Java runtime is available.
base: core20
confinement: strict
grade: stable

apps:
  pava:
    command: bin/pava
    plugs: [network]

parts:
  pava:
    plugin: nil
    source: .
    build-packages:
      - maven
      - openjdk-17-jdk   # Adjust this if the package name differs in the builder environment
    override-build: |
      set -e
      # Build the project using Maven
      mvn clean package
      # Create the destination directory for the shell script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      # Copy the jar produced by Maven (adjust path if needed)
      cp target/pava.jar $SNAPCRAFT_PART_INSTALL/
      # Copy the shell script into the bin directory so it becomes the command entrypoint
      cp pava $SNAPCRAFT_PART_INSTALL/bin/
